CC=clang++
CXXFLAGS= -g -Wall -std=c++23

bin/day1: 1/main.cpp
	$(CC) $(CXXFLAGS) 1/main.cpp -o bin/day1

bin/day2: 2/main.cpp
	$(CC) $(CXXFLAGS) 2/main.cpp -o bin/day2

bin/day3: 3/main.cpp
	$(CC) $(CXXFLAGS) 3/main.cpp -o bin/day3

bin/day4: 4/main.cpp
	$(CC) $(CXXFLAGS) 4/main.cpp -o bin/day4

clean:
	rm -rf bin/*

