CC=clang++ -std=c++23

bin/day1: 1/main.cpp
	$(CC) -g 1/main.cpp -o bin/day1

bin/day2: 2/main.cpp
	$(CC) -g 2/main.cpp -o bin/day2

bin/day3: 3/main.cpp
	$(CC) -g 3/main.cpp -o bin/day3

clean:
	rm -rf bin/*

